# Google Cloud Build configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/lstm-sentiment-api:latest',
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/lstm-sentiment-api:latest'
    ]
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lstm-sentiment-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lstm-sentiment-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '0.5'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/lstm-sentiment-api:latest'
